### ISSUE TITLE
Subscribe form not working.

### ISSUE THREAD

**Issue by michalrames** [mailjet/joomla-mailjet-plugin-apiv3#20]
This is the code in the submission handler. The url is relative and results in http://www.host.com/whatever/the/current/path/is/index.php which returns 404.

What is supposed to be the correct url? `<?php echo JRoute::_('index.php'); ?>` ?:

`jQuery(document).ready(function($){`
`       $('.mailjet-subscribe').submit(function(e) {`
`           e.preventDefault();`
`           var f = $(e.currentTarget);`
`           var p = f.parent();`
`           $.ajax({`
`               type: "POST",`
**`               url: "index.php",`**    <--- The line in question
`               data: f.serialize(),`
`               dataType: "json",`
`               success: function(data){  ... },`
`               error: function() {  ...   }`
`           });`
`       });`
`   });`
`

Thanks

**Comment by michalrames** [comment]
Turns out this is due to insufficient error/exception handling - when the contact already exists in the list, the  form POST returns 404. 

Is there any active community/developers around this plugin?

**Comment by mskochev** [comment]
Hello michalrames,

Thanks for reporting this issue. We are working on fixing it.

Best regards,
Mailjet plugins team

**Comment by mskochev** [comment]
Hello michalrames,

We have released an update (3.1.10) where the reported issue should be resolved. Please can you test and let us know if it works for you.

Thanks,
Mailjet Plugins Team

**Comment by michalrames** [comment]
Hi, 

I can confirm that the widget now displays a better error message. Thank you! 

I found two minor issues with the current distribution:

* The package, component, and the module version is showing 3.1.7 and 3.1.9  - it's a little confusing, can you please update the version labels and dates in the metadescriptors? 

* The mod_mailjet and com_mailjet are nested inside the package several times. This doesn't seem to cause any issues.

Also, would you consider adding the source code directly to code repository? That way it would be easier to make forks, pull requests, etc...

**Comment by mskochev** [comment]
Hello michalrames,

Thanks for you validation and the suggestions. We will provide a next release resolving the two mentioned issues.

Best regards,
Mailjet Plugins Team
